export const users = [
  {
    employee_id: 1,
    name: "John Doe",
    role: "Regional Manager",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    is_active: true,
  },
  {
    employee_id: 2,
    name: "Jane Smith",
    role: "Inventory Manager",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    is_active: true,
  },
  {
    employee_id: 3,
    name: "Michael Brown",
    role: "Store Manager",
    image: null,
    is_active: false,
  },
  {
    employee_id: 4,
    name: "Emily White",
    role: "Cashier",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    is_active: true,
  },
  {
    employee_id: 5,
    name: "Chris Johnson",
    role: "Store Manager",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    is_active: true,
  },
  {
    employee_id: 6,
    name: "Anna Davis",
    role: "Inventory Manager",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    is_active: false,
  },
  {
    employee_id: 7,
    name: "David Martinez",
    role: "Regional Manager",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    is_active: true,
  },
  {
    employee_id: 8,
    name: "Sarah Miller",
    role: "Cashier",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    is_active: true,
  },
  {
    employee_id: 9,
    name: "James Wilson",
    role: "Store Manager",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    is_active: false,
  },
  {
    employee_id: 10,
    name: "Lisa Garcia",
    role: "Regional Manager",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    is_active: true,
  },
];
